---
version: "3.3"
services:
  sd-single-node:
    build:
      context: dockerfiles/
      dockerfile: dockerfile-stardog
      args:
        - STARDOG_TAG=${STARDOG_TAG}
        - STARDOG_REPO=${STARDOG_REPO}
        - NODE_TYPE=single
    container_name: ${STARDOG_HOSTNAME_SINGLE_NODE}
    entrypoint: ["/bin/bash", "-c"]
    command: ["/var/start.sh"]
    ports:
      - "127.0.0.1:5820:5820"

  # two mysql servers are used instead of one so we can simulate multiple datasources.
  mysql-music:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-mysql-music
    # this value is hardcoded in conftest.py (music_options fixture), for multiple datasource / vg tests.
    # it's also hardcoded in test/test_admin.py for testing imports.
    container_name: pystardog_mysql_music

  mysql-videos:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-mysql-videos
    container_name: pystardog_mysql_videos