# Note that circleci docker executor does not allow to volume mounting, hence the volume block can't be used here.
# https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-use-Docker-volume-mounting-on-CircleCI-
# For this reason, we are creating specific dockerfiles, and building the images from them, copying the files in the images
# instead of mounting them.
version: "3.3"
services:
  stardog:
    build:
      context: dockerfiles/
      dockerfile: dockerfile-stardog
    container_name: pystardog_stardog
  tests:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-python
    entrypoint: /bin/bash -c
    command: ["./utils/run_tests.sh"]
    container_name: pystardog_tests
  mysql:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile-mysql
    container_name: pystardog_mysql

