ARG STARDOG_TAG
ARG STARDOG_REPO
FROM ${STARDOG_REPO}:${STARDOG_TAG}

USER root
RUN yes $SSH_PASS | passwd $SSH_USER
RUN apt-get update -y && apt-get install openssh-server vim unzip wget -y

ARG CONNECTOR_VERSION=8.0.21

RUN wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-${CONNECTOR_VERSION}.zip \
  && unzip mysql-connector-java-${CONNECTOR_VERSION}.zip \
  && mv mysql-connector-java-${CONNECTOR_VERSION}/mysql-connector-java-${CONNECTOR_VERSION}.jar opt/stardog/server/dbms/mysql-connector-java.jar

ARG NODE_TYPE
ARG SSH_USER
ARG SSH_PASS

COPY stardog-license-key.bin /var/opt/stardog
COPY start.sh /var/start.sh
COPY start-standby.sh /var/start-standby.sh
COPY example.ttl /tmp/example-remote.ttl

USER stardog
# We require ssh to test that backups are successfully generated.
# We are considering the option of move to circleci machine executor that allows mounting volumes, which could
# make this easier in the future. We might still require ssh for tests that require restarting a stardog server.
RUN mkdir ${HOME}/custom_ssh && \
    ssh-keygen -f ${HOME}/custom_ssh/ssh_host_rsa_key -N '' -t rsa && \
    ssh-keygen -f ${HOME}/custom_ssh/ssh_host_dsa_key -N '' -t dsa && \
    echo -e "Port 2222 \n\
    HostKey ${HOME}/custom_ssh/ssh_host_rsa_key \n\
    HostKey ${HOME}/custom_ssh/ssh_host_dsa_key \n\
    AuthorizedKeysFile  .ssh/authorized_keys \n\
    ChallengeResponseAuthentication no \n\
    UsePAM yes \n\
    Subsystem   sftp    /usr/lib/ssh/sftp-server \n\
    PidFile ${HOME}/custom_ssh/sshd.pid" > ${HOME}/custom_ssh/sshd_config



COPY stardog.$NODE_TYPE.properties /var/opt/stardog/stardog.properties


